# This yaml serves to define the AWS tags that willl be applied to all resources in this cluster
# This is useful for keeping track of billing & identifying where we're spending our moolah
---

Environment : infra_dev_cluster
Owner       : devops
Service     : infrastructure
Repo        : terraform/infra_dev_cluster