# Generated by Terragrunt. Sig: nT10x157tbuaRZEa
terraform {
  backend "s3" {
   bucket = "thentwrk-tf-state"
   dynamodb_table = "tf-lock-state"
   encrypt = true
   key = "terraform-data/ip_whitelisting/terraform.tfstate"
   region= "us-east-1"
  }
} 